// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqbhsowztsxwmjnmsgqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYmhzb3d6dHN4d21qbm1zZ3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzc3OTgsImV4cCI6MjA1Njk1Mzc5OH0._He1AM3Zbu5VJgQ-lU5UnDIupZ72vqr5PFdMLKj_dWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);